[[main]]
  name = "GitHub"
  url = "https://github.com/unikernelalliance"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/unikernelalliance/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/unikernelalliance"
  weight = 30
